language: php

php:
  - '7.4'

before_install:
  - composer install

script:
  - ./vendor/bin/codecept run
  - ./vendor/bin/phpcs --standard=PSR2 src web
  - ./vendor/bin/psalm --show-info=true src web
